name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build lpp
        run: npm run build --if-present

      - name: Upload lpp artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpp
          path: dist/withL10n.global.js

      - name: Build lpp (Turbowarp)
        run: npm run build:turbowarp --if-present

      - name: Upload lpp-turbowarp artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpp-turbowarp
          path: dist/index.global.formatted.js
